config/routes.rb
Rails.application.routes.draw do

  resources :guidelines

  post '/aws', to: 'aws#get'

  get '/chat', to: 'chat#show'
  post '/current_user', to: 'chat#current'
  post '/chat', to: 'chat#create'
  post '/refresh_ttl', to: 'appearance#refresh'

  get '/bluejeans', to: 'collected_urls#new'
  resources :collected_urls
  get '/bluejeans/public_fields', to: 'collected_urls#get_public_fields'
  get '/collected_urls/public_fields', to: 'collected_urls#get_public_fields'
  get '/check_your_email', to: 'pages#check_your_email'
  resources :trees
  resources :file_sets
  resource :browser, only: :show
  get 'browser/transcription', to: 'browsers#transcription'
  get 'browser/index', to: 'browsers#index'
  get 'browser/tabs', to: 'browsers#tabs'
  resource :recorder, only: :show
  resources :transcripts
  

  get 'password_resets/new'

  get 'password_resets/edit'

  get :echo, to: 'pages#echo'
  root 'pages#home'
  get :help, :to => 'pages#help'
  get :about_study, to: 'pages#about'
  get :consent, to: 'pages#consent'
  get :waveform_help_screen, to: 'pages#waveform_help_screen'
  get :service_help_screen, to: 'pages#service_help_screen'
  get :level_testing_page, to: 'pages#level_testing_page'
  get :compatibility, to: 'pages#compatibility'
  get :documentation, to: 'pages#documentation'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/confirmation', to: 'sessions#confirmation'
  post '/confirm', to: 'sessions#confirm'
  delete '/logout', to: 'sessions#destroy'
  get '/logout2', to: 'sessions#destroy2'
  get '/update_namespaces', to: 'servers#get_tools'
  get '/servers/ntl', to: 'servers#glg'
  get '/ntl', to: 'glg#index'
  post '/ntl/play', to: 'glg#play'
  get '/webtrans', to: 'glg#windex'
  post '/webtrans/play', to: 'glg#wplay'
  get '/ntl/consent', to: 'glg#consent'
  post '/users/single', to: 'users#single'
  resources :servers
  resources :users
  post "/users/create_enrollment", to: "users#create_enrollment"
  resources :sessions, only: [:create]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :kit_batches, only: [ :index, :show, :new, :create ]
  resources :user_defined_objects, as: :user_defined_objects

  resources :annotations
  get '/preann', to: 'annotations#preann'
  resources :reports

  resources :project_builder, only: [:new]
  get 'project_builder/project', :to => 'project_builder#project'
  get 'project_builder/choose_project', :to => 'project_builder#choose_project'
  get 'project_builder/task', :to => 'project_builder#task'
  get 'project_builder/choose_task', :to => 'project_builder#choose_task'
  get 'project_builder/dataset', :to => 'project_builder#dataset'
  get 'project_builder/choose_dataset', :to => 'project_builder#choose_dataset'
  get 'project_builder/tool', :to => 'project_builder#tool'
  get 'project_builder/template', :to => 'project_builder#template'
  patch 'project_builder/create_template', :to => 'project_builder#create_template'
  get 'project_builder/widget', :to => 'project_builder#widget'
  get 'project_builder/templateselection', :to => 'project_builder#templateselection'
  post 'project_builder/create_widget', :to => 'project_builder#create_widget'
  post 'projects/respond_with_project', :to => 'projects#respond_with_project'
  get 'projects/:id/research_team', :to => 'projects#research_team', :as => 'projects_research_team'
  get 'projects/:id/users_not_in_project', to: 'projects#users_not_in_project', :as => 'users_not_in_project'
  get 'groups/:id/users_not_in', to: 'groups#users_not_in', :as => 'users_not_in'
  get 'projects/:id/project_users', to: 'projects#project_users', :as => 'project_project_users'
  get 'tasks/:id/task_users', to: 'tasks#task_users', :as => 'task_task_users'
  post 'tasks/respond_with_task', :to => 'tasks#respond_with_task'
  get 'tasks/recreate', :to => 'tasks#recreate'
  post 'data_sets/respond_with_dataset', :to => 'data_sets#respond_with_dataset'

  post 'add_user_to_project_and_task/:project_id/:task_id', :to => 'projects#add_user_to_project_and_task', :as => 'add_user_to_project_and_task'


  get "/image_description", to: "image_description#index"

  get "/level_testing", to: "level_testing#index"



  get 'class_defs_index2', to: "class_defs#index2"
  post 'editclassdef', to: "class_defs#editclassdef"
  resources :node_classes
  resources :nodes
  resources :trees
  resources :node_values
  resources :nde_values
  resources :constants
  resources :kit_batches, only: [ :index, :show, :new, :create ]
  resources :tasks, :except => [:new, :create]#if the task already exists, we can infer the project, for new/create it must be specified
  resources :preference_types
  resources :preference_settings
  resources :projects, except: [ :new, :edit ] do
    resources :tasks, except: [ :new, :edit, :index ] do
      member do
        get :kit_creator
        post :file_upload
        post :kit_generation_preview
        post :generate_kits
        post :process_kits
        post :process_kits_preview
        get :reassign_kit
        get :kit_processor
        patch :reassign_many_kits
      end
    end
  end
  resources :task_users, :only => [ :show, :create, :update, :destroy ]
  resources :project_users
  post "/project_users/invite", to: "project_users#invite", as: "project_users_invite"
  post "/users/invite", to: "users#invite", as: "users_invite"
  # resources :kit_types
  # resources :class_defs
  # resources :node_values
  # resources :node_values
  # resources :node_values
  get "/kits/all", to: 'kits#all'
  get "/kits_new", to: 'kits#kits_new'
  post "/create_kits_from_kits_tab", to: 'kits#create_kits_from_kits_tab'
  resource :kits do
    member do
      get ':id/unlock_tree', action: :unlock_tree, as: :unlock_tree
      get :get
      patch :change_kit_state
      post :get_time_spent
      get :get_time_spent
      post :change_time_spent
      get :change_time_spent
      post :get_message_from_journal
      post :mongo_results
      get :mongo_query
      get ':id/show', :action => :show, :as => :show
      patch ':id/update', :action => :update, :as => :update
      get 'task/:id', :action => :task, :as => :task
      post :set_kits_done
      get 'fix_floating_kits/:task/:new_state', :action => :fix_floating_kits, :as => :fix_floating_kits
      get :management
      get :trouble
      get ':id/undo', action: :undo
    end
  end
  post '/duration', to: 'kits#duration'

  resources :workflows do
    member do
      get 'read_only/:kit_id', to: 'task_users#read_only'
      # get 'quality_control/:kit_id/:task_id', :action => 'quality_control'
      get 'work/:workflow_id', to: 'task_users#get'
      # get 'work/:task_user_id/:value', :action => 'work'
      get 'set/:task_user_id/:value', :action => 'set'
      # get 'set_lock/:state', :action => 'set_lock'
    end
  end
  resources(:class_defs) do
    resources :node_classes do
      member do
        post :add_child
      end
    end
    member do
      get :css
      get :edit_css
      post :update_css
      get :tree_viewer
      get :preview
      get :release
      post :clone
      post :update_bootstrap_mode
      post :increment_version
      get 'set_lock/:state', :action => :set_lock
      get :tables
      get :create_tables
    end
  end

  resources :kit_types do
    get 'autocomplete', :on => :collection
    member do
      patch :update_name
      patch :update_type
      patch :update_meta
      patch :update_constraints
    end
  end
  resources :styles do
    member do
      post 'style_manager/:cid', :action => :style_manager
      post 'add_style/:cid', :action => :add_style
      post :add_property
    end
  end

  resources :games
  resources :game_variants do
    get 'autocomplete', :on => :collection
  end

  resources :data_sets do
    member do
      get 'get_urls'
    end
  end

  resource :sources do
    member do
      get :text
      get :audio
      get :audio_full
      post :get_text
      post :get_ner
      post :uget
      get :ugett
      post :uget_public
      get :get_upload
      get :get_download
      get :new
    end
  end

  resource :file_set do
    member do
      get :get_uploads
    end
  end

  resources :languages do
    get 'autocomplete', :on => :collection
  end

  resources :demographic_profiles
  resources :groups, except: [ :new, :edit ]
  resources :group_users, :only => [:create, :destroy]

  resources :enrollments do
    member do
      get :withdrawn
      post :toggle_participant_active
      post :update_demographics
    end
  end

  resources :collections
  resources :invites
  resources :features, except: [ :new, :edit ]
  resources :scripts, except: [ :new, :edit ]

  get '/bucket', to: 'data_sets#bucket'
  post '/token', to: 'cognito_token#get_credentials'

end

app/controllers/kit_types_controller.rb
class KitTypesController < ApplicationController
  include KitTypesHelper

  before_action :authenticate

  def autocomplete
    @kit_types = KitType.order(:name).where("name LIKE ?", "%#{params[:term]}%").map(&:name).to_json
    respond_to do |format|
      format.json { render json: @kit_types }
    end
  end

  def index
    respond_to do |format|
      format.json do
        render json: (
          if lead_annotator?
            KitType.sorted.all.map(&:attributes)
          else
            { error: 'Permission denied.' }
          end
        )
      end
    end
  end

  def show
    respond_to do |format|
      format.json do
        render json: (
          if lead_annotator?
            kit_type = KitType.find(params[:id])
            if kit_type.meta['root'].nil?
              kit_type.meta['root'] = NodeClass.where(parent_id: NodeClass.find_by_name('Root')).last.name
              kit_type.save
            end
            if kit_type.meta['js'].nil?
              kit_type.meta['js'] = 'empty'
              kit_type.save
            end
            node_class = NodeClass.where(name: kit_type.meta['root']).first_or_create
            kit_type.update(node_class_id: node_class.id)
            {
              id: kit_type.id,
              name: kit_type.name,
              node_class_id: node_class.id,
              node_classes: NodeClass.sorted_root_nodes.map { |x| { id: x.id, name: x.name.split(':').first } },
              # feature_files: feature_files,
              # manifest: kit_type.constraints.has_key?('manifest')
              constraints: kit_type.constraints,
              features: Feature.where(category: 'kit_type').map(&:attributes)
            }
          else
            { error: 'Permission denied.' }
          end
        )
      end
    end
  end


  def create
    respond_to do |format|
      format.json do
        render json: (
          if not lead_annotator?
            { error: "Only a project manager can create a kit type." }
          else
            kit_type = KitType.new kit_type_params
            kit_type.meta = {}
            kit_type.node_class_id = NodeClass.where(parent_id: NodeClass.find_by_name('Root')).last.id
            kit_type.constraints = {}
            if kit_type.save
              kit_type.attributes
            else
              { error: kit_type.errors.full_messages }
            end
          end
        )
      end
    end
  end
    # params[:kit_type][:constraints].split(" ").each {|x| @kit_type.constraints.store(x, "")}

  def edit
    show_helper
    respond_to do |format|
      format.html do
        html = render_to_string partial: 'show'
        render json: { html: html }
      end
    end
  end

  def update
     respond_to do |format|
       format.json do
         kit_type = KitType.find params[:id]
         render json: (
           if not lead_annotator?
             { error: "Only a project manager can edit a kit type." }
           elsif params[:node_class_id]
             kit_type.node_class_id = params[:node_class_id].to_i
             if kit_type.save
               kit_type
             else
                { error: kit_type.errors.full_messages }
              end
           elsif params[:constraints]
             Feature.where(category: 'kit_type').uniq.each do |x|
               if params[:constraints].has_key? x.name
                 if x.name == x.value
                   if params[:constraints][x.name]
                     kit_type.constraints[x.name] = x.name
                   else
                     kit_type.constraints.delete x.name
                   end
                 else
                   if params[:constraints][x.name] and (params[:constraints][x.name].class != String or params[:constraints][x.name].length > 0)
                     kit_type.constraints[x.name] = params[:constraints][x.name]
                   else
                     kit_type.constraints.delete x.name
                   end
                 end
               end
             end
             if kit_type.save
               kit_type
             else
                { error: kit_type.errors.full_messages }
              end
           elsif kit_type.update kit_type_params
             kit_type
           else
             { error: kit_type.errors.full_messages }
           end
         )
       end
     end
   end

  def update_name
    @kit_type = KitType.find params[:id]
    @kit_type.name = params[:kit_type][:name]
    save_kit_type("Name updated to #{@kit_type.name}.")
    redirect_back(fallback_location: root_path)
  end

  # def update_type
  #   @kit_type = KitType.find params[:id]
  #   @kit_type.type = params[:kit_type][:type]
  #   save_kit_type("Type updated to #{@kit_type.type}.")
  #   redirect_back
  # end

  def update_constraints
    @kit_type = KitType.find params[:id]
    @kit_type.constraints = {}
    # params[:kit_type][:constraints].split(" ").each {|x| @kit_type.constraints.store(x, "")}
    if params[:constraints2]
      @kit_type.constraints = YAML.load params[:constraints2]
    else
      params.each do |k, v|
        next if k.in? %w[ utf8 _method authenticity_token commit controller action id ]
        @kit_type.constraints[k] = v
      end
    end
    save_kit_type("Features set: #{@kit_type.constraints.keys()}.")
    redirect_back(fallback_location: root_path)
  end

  # def update_meta
  #   @kit_type = KitType.find params[:id]
  #   @kit_type.meta['root'] = params[:kit_type][:root]
  #   @kit_type.meta['js'] = params[:kit_type][:js]
  #   @kit_type.meta['empty_list'] = params[:kit_type][:empty_list]
  #   @kit_type.meta['coref_groups'] = params[:kit_type][:coref_groups].split(',')
  #   @kit_type.meta['view'] = params[:kit_type][:view]
  #   @kit_type.meta['template'] = params[:kit_type][:template]
  #   @kit_type.meta['source'] = params[:kit_type][:source]
  #   save_kit_type("Meta updated to #{@kit_type.meta.to_s[0..100]}...")
  #   redirect_back
  # end

  def destroy
    respond_to do |format|
      format.json do
        render json: (
          if not lead_annotator?
            { error: "Only a project manager can delete a kit_type." }
          else
            kit_type = KitType.find(params[:id])
            kit_type.destroy
            { deleted: "kit_type: #{kit_type.name} has been deleted." }
          end
        )
      end
    end
  end

  private

  def kit_type_params
    params.require(:kit_type).permit(:name, :node_class_id, :source_id, :config_id, :meta, :annotation_set_id, :constraints)
  end

  def save_kit_type(success_str)
    @kit_type.save ? flash[:success] = success_str : flash[:error] = @kit_type.errors.full_messages.join(", ")
  end

end

app/helpers/kit_types_helper.rb
module KitTypesHelper
  def js_files
    jsfiles = Array.new
    Dir['app/assets/javascripts/workflows/*.js'].each do |file|
      jsfiles << file.gsub('.js', '').gsub('app/assets/javascripts/workflows/', '')
    end
    Dir['app/assets/javascripts/workflows/*.coffee'].each do |file|
      jsfiles << file.gsub('.js.coffee', '').gsub('app/assets/javascripts/workflows/', '')
    end
    jsfiles.sort!#list of possibilities for meta['js']
  end
  
  def template_files
    templates = Array.new
    Dir['app/views/kit_types/kit_type/*.haml'].each do |file|
      templates << file.gsub('.js', '').gsub('app/views/kit_types/kit_type/', '')
    end
    templates.sort!#list of possibilities for meta['template']
  end
end

app/views/kit_types/_dialogs.html.haml
#message_dialog
#confirm_dialog
#document_viewer_dialog
#legend_dialog{:title => 'Legend'}
%script
  $('.edit_node_class_modal').on('hidden', function(){
  window.location.reload();
  });
.modal#tree_locked_modal
  .modal-fade-screen
    .modal-inner
      .modal-close
      %h3
        This kit is locked.
      #current_locked
        %div
          As the owner, you may unlock the kit.
        %button#tree_locked_modal_submit{ kit_id: @kit.id }
          Unlock
/ .modal.hide.fade#file_upload_modal
/   .modal-header
/     %button.close{:type => 'button', :data => {:dismiss => 'modal'}, :"aria-hidden" => true} &times;
/     %h3 Confirm upload

/   .modal-body
/     Are you sure?
/   .modal-footer
/     %button.btn.btn-primary#file_upload_modal_submit Submit
/     %button.btn{:data => {:dismiss => 'modal'}, :"aria-hidden" => 'true'} Cancel
/ .modal.hide.fade#file_choice_modal
/   .modal-header
/     %button.close{:type => 'button', :data => {:dismiss => 'modal'}, :"aria-hidden" => true} &times;
/     %h3 Choose file

/   .modal-body
/   .modal-footer
/     %button.btn{:data => {:dismiss => 'modal'}, :"aria-hidden" => 'true'} Cancel
/ .modal.hide.fade#listitem_move_modal
/   .modal-header
/     %button.close{:type => 'button', :data => {:dismiss => 'modal'}, :"aria-hidden" => true} &times;
/     %h3 Move ListItem

/   .modal-body
/     Move item in position
/     %span
/       x
/     to position
/     %input{ type: 'text' }
/     .div
/       remember that the first position is position 0, not 1
/   .modal-footer
/     %button.btn.btn-primary#listitem_move_modal_submit Submit
/     %button.btn{:data => {:dismiss => 'modal'}, :"aria-hidden" => 'true'} Cancel

app/views/kit_types/_features.html.haml
%div.features
  = f.submit "Save All Features", :id => "submit_meta", :class => 'btn', data: { confirm: "Are you sure? Will affect #{@task_ids_names.size} task(s)." } if @task_ids_names.size > 1
  = f.submit "Save All Features", :id => "submit_meta", :class => 'btn' if @task_ids_names.size <= 1
  / %strong Constraints (separate with spaces)
  %div
    Currently WebAnn has the following contraints:
  = @kit_type.constraints.to_s
  %div{ style: 'height: 500px; overflow: auto' }
    - extra.each do |a|
      %div.feature
        %label.checkbox
          - case a[0]
          - when 'checkbox'
            = check_box_tag_helper a[1]
            = a[2]
        = a[3]
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'controls_at_top'
        Control buttons at top
      Puts the control buttons (e.g. Next) at the top of the kit.
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'rtl'
        Right to Left
      type in this contraints for languages that read from right to left
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'restricted_event_types'
        Restricted event types
      restricted_event_types: this is relevant to Rich ERE which restricts event types and subtypes to a limited inventory for 2016's eval data annotation
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'specific_group'
        Specific Group
      specific_group: this is relevant to Rich ERE which restricts entity specificity value to a new sets of drop down menu
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'comment'
        Comment pop up
      comment: use this contraint if you want to allow a pop up window for each kit for annotators to leave comments
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'ban-quotes'
        Ban quotes
      ban-quotes: use this contraint if you want to gray out content within <quote> </quote> from an XML source document, such as DF in ERE
    / %div.feature
    /   %label.checkbox
    /     = check_box_tag_helper 'orgper'
    /     Limit to orgper
    /   orgper: for EDL tools, limits to org and per entities and search
    / %div.feature
    /   %label.checkbox
    /     = check_box_tag_helper 'gpeloc'
    /     Limit to gpeloc
    /   gpeloc: for EDL tools, limits to gpe and loc entities and search
    / %div.feature
    /   %label.checkbox
    /     = check_box_tag_helper 'perorg'
    /     Limit to perorg
    /   perorg: for EDL tools, limits to per and org entities and search
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'segment_lines'
        Segment lines
      ?
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'para'
        Paragraphs
      ?
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'nu'
        Nu
      ?
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'arabic_text'
        arabic_text
      ?
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'hide_entity'
        hide_entity
      ?
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'hide_underlines'
        hide_underlines
      ?
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'reported_and_resolved_can_be_empty'
        reported_and_resolved_can_be_empty
      ?
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'separate_doc'
        separate_doc
      ?
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'hide-search'
        hide-search
      ?
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'force_coref_finished'
        force_coref_finished
      ?
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'rl'
        rl
      ?
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'show_coref_finished'
        show_coref_finished
      ?
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'deprecated'
        Deprecated button
      Adds a button to the control panel for marking the kit deprecated.
    / %div.feature
    /   %label.checkbox
    /     = check_box_tag_helper 'all_cace_ere_features'
    /     CACE ERE features
    /   Adds a button to the control panel for marking the kit deprecated.
    %div.feature
      %div{ style: 'display: flex' }
        %strong
          tablecinner_limit
        = text_field_tag_helper 'tablecinner_limit'
      Sets length limit on table
    %div.feature
      %div{ style: 'display: flex' }
        %strong
          edl_search_parameters
        = text_field_tag_helper 'edl_search_parameters'
      Sets EDL search parameters:  (orgper|gpeloc) (...)
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'cace_source'
        CACE source
      cace source
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'manifest'
        manifest
      Source input is a json manifest file
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'web_audio'
        Web Audio
      web audio
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'audio1'
        audio1
      web audio
    %div.feature
      %label.checkbox
        = check_box_tag_helper 'lorelei_il_nom'
        lorelei IL nom annotation
      changes to full entity tool for lorelei IL nom annotation
    / # = text_field_tag "kit_type[constraints]", @kit_type.constraints.keys()

app/views/kit_types/_show.html.haml
%div
  %div
    %div
      %strong Name:
      = @kit_type.name
      %button.expand-trigger.expand-hidden Edit
      .expand-content
        = form_for @kit_type, :as => :kit_type, :url => update_name_kit_type_path(@kit_type), :html => {:autocomplete => 'off'} do |f|
          = f.text_field :name
          = f.submit "Save", :id => "submit_name", :class => 'btn margin-bottom-10', data: { confirm: "Are you sure? Will affect #{@task_ids_names.size} task(s)." } if @task_ids_names.size > 1
          = f.submit "Save", :id => "submit_name", :class => 'btn margin-bottom-10' if @task_ids_names.size <= 1
    %div
      %strong Type:
      / # = @kit_type.type
      %button.expand-trigger.expand-hidden Edit
      .expand-content
        = form_for @kit_type, :as => :kit_type, :url => update_type_kit_type_path(@kit_type), :html => {:autocomplete => 'off'} do |f|
          / # = select_tag "kit_type[type]", options_for_select(@kit_type.types, @kit_type.type)
          = f.submit "Save", :id => "submit_name", :class => 'btn margin-bottom-10', data: { confirm: "Are you sure? Will affect #{@task_ids_names.size} task(s)." } if @task_ids_names.size > 1
          = f.submit "Save", :id => "submit_name", :class => 'btn margin-bottom-10' if @task_ids_names.size <= 1
      .row-fluid
        %strong Node Class:
        = @kit_type.node_class_id
      
      .row-fluid
        %strong Config:
        = @kit_type.config_id
      
      .row-fluid
        %strong Tasks using this kit type:
        %button.expand-trigger.expand-hidden View task list
        .expand-content
          -@task_ids_names.each do |t|
            %div
              =t
      %div
        %strong Meta:
        / .inline= @kit_type.meta
        %button.expand-trigger.expand-hidden Edit
        .expand-content
          = form_for @kit_type, :as => :kit_type, :url => update_meta_kit_type_path(@kit_type), :html => {:autocomplete => 'off'} do |f|
            %strong Meta
            .field{:style => "margin-left: 15px;"}
              .row-fluid
                %strong Root
              / # = select_tag "kit_type[root]", options_for_select(@roots2, @kit_type.meta['root']), :prompt => "Select one"
            .field{:style => "margin-left: 15px;"}
              .row-fluid
                %strong JavaScript File
              / # = select_tag "kit_type[js]", options_for_select(@jsfiles2, @kit_type.meta['js']), :prompt => "Select one"
            .field{:style => "margin-left: 15px;"}
              .row-fluid
                %strong Lists to start as empty
              / # = select_tag "kit_type[empty_list]", options_for_select(@all_lists2, @kit_type.meta['empty_list']), :multiple => true, :size => @all_lists2.length
            .field{:style => "margin-left: 15px;"}
              .row-fluid
                %strong Coref Groups (comma separated list)
              / # = text_field_tag "kit_type[coref_groups]", @kit_type.meta['coref_groups'] ? @kit_type.meta['coref_groups'].join(',') : ''
            .field{:style => "margin-left: 15px;"}
              .row-fluid
                %strong View
              / # = text_field_tag "kit_type[view]", @kit_type.meta['view']
              
            .field{:style => "margin-left: 15px;"}
              .row-fluid
                %strong Template
              / # = select_tag "kit_type[template]", options_for_select(@templates2, @kit_type.meta['template']), :prompt => "Select one"
            .field{:style => "margin-left: 15px;"}
              .row-fluid
                %strong Source (JSON)
              / # = text_field_tag "kit_type[source]", @kit_type.meta['source']
            = f.submit "Save", :id => "submit_meta", :class => 'btn', data: { confirm: "Are you sure? Will affect #{@task_ids_names.size} task(s)." }  if @task_ids_names.size > 1 
            = f.submit "Save", :id => "submit_meta", :class => 'btn' if @task_ids_names.size <= 1
      %div
        %strong Constraints toggles
        .inline= @kit_type.constraints.keys()
        %button.expand-trigger.expand-hidden Edit
        .expand-content
          = form_for @kit_type, :as => :kit_type, :url => update_constraints_kit_type_path(@kit_type), :html => {:autocomplete => 'off'} do |f|
            .field{:style => "margin-left: 15px;"}
              .row-fluid
                %strong Constraints (separate with spaces)
                %div
                  Currently WebAnn has the following contraints:
                %div
                  rtl (right to left) : type in this contraints for languages that read from right to left
                %div
                  restricted_event_types: this is relevant to Rich ERE which restricts event types and subtypes to a limited inventory for 2016's eval data annotation
                %div
                  specific_group: this is relevant to Rich ERE which restricts entity specificity value to a new sets of drop down menu
                %div
                  comment: use this contraint if you want to allow a pop up window for each kit for annotators to leave comments 
                %div
                  ban-quotes: use this contraint if you want to gray out content within <quote> </quote> from an XML source document, such as DF in ERE
                %div
                  orgper: for EDL tools, limits to org and per entities and search
                %div
                  gpeloc: for EDL tools, limits to gpe and loc entities and search
                %div
                  If you want to add multiple constraints, type in each constraint, with white space separate each
                %div
                  List constraints to toggle separated by spaces
                = text_field_tag "kit_type[constraints]", @kit_type.constraints.keys()
                = f.submit "Save", :id => "submit_meta", :class => 'btn', data: { confirm: "Are you sure? Will affect #{@task_ids_names.size} task(s)." } if @task_ids_names.size > 1
                = f.submit "Save", :id => "submit_meta", :class => 'btn' if @task_ids_names.size <= 1
    %td.sidebar.round
      .row-fluid
        %strong Created: 
        = @kit_type.created_at.to_date
      .row-fluid
        %strong Last Updated: 
        = @kit_type.updated_at.to_date
      
%ul.pager
  %li=link_to "Return to kit types", kit_types_path
      